"use client";

import { ArrowRight, Blocks, ShieldCheck, Terminal } from "lucide-react";
import Link from "next/link";
import { Logo } from "@/components/brand/logo";

const tracks = [{ icon: Terminal, title: "Prompt Security", copy: "Probe model behavior and learn how prompt injection works in controlled labs." }, { icon: ShieldCheck, title: "Defense Patterns", copy: "Build practical safeguards for the models your team is shipping." }, { icon: Blocks, title: "Sandboxed Labs", copy: "Practice against realistic scenarios without touching production systems." }];

export default function LandingPage() {
    return <main className="landing-page"><header className="landing-header"><Logo /><nav><a href="#tracks">Learning tracks</a><a href="#workspace">For teams</a><Link href="/signin">Sign in</Link><Link className="landing-header-button" href="/signup">Get started <ArrowRight size={14} /></Link></nav></header><section className="landing-hero"><div className="hero-copy"><p className="eyebrow">LLMENTOR / SECURITY TRAINING SYSTEM</p><h1>Learn the edge<br /><span>before it ships.</span></h1><p>LLMentor is a hands-on security workspace for people building with language models. Learn the attack paths, test the defenses, and leave with better instincts.</p><div className="hero-actions"><Link className="landing-primary" href="/signup">Start learning <ArrowRight size={16} /></Link><Link className="landing-secondary" href="/signin">View the workspace</Link></div></div><div className="hero-terminal"><div className="terminal-bar"><span>LAB / INTRO-001</span><span>● ● ●</span></div><div className="terminal-body"><p><span>01</span> $ mentor init security-track</p><p className="terminal-success">[ok] sandbox provisioned</p><p><span>02</span> $ inspect threat_model</p><p className="terminal-warning">[!!] prompt injection detected</p><p><span>03</span> $ apply defense --strict</p><p className="terminal-success">[ok] model boundary secured</p><div className="terminal-cursor">_</div></div></div></section><section className="landing-stats" id="workspace"><div><strong>01</strong><span>CONTROLLED<br />EXPERIMENTS</span></div><div><strong>24</strong><span>SECURITY<br />LABS</span></div><div><strong>∞</strong><span>ROOM TO<br />PRACTICE</span></div><p>Built for students, researchers, and teams that take model security seriously.</p></section><section className="tracks-section" id="tracks"><div className="section-kicker"><span>01 / CORE TRACKS</span><span>WHAT YOU WILL PRACTICE</span></div><div className="track-grid">{tracks.map(({ icon: Icon, title, copy }, index) => <article className="track-card" key={title}><span className="track-number">0{index + 1}</span><Icon size={23} /><h2>{title}</h2><p>{copy}</p><Link href="/signup">Explore track <ArrowRight size={14} /></Link></article>)}</div></section><footer className="landing-footer"><Logo compact /><span>LLMentor Security Lab Platform</span><span>STATUS: ALL SYSTEMS NOMINAL</span></footer></main>;
}
